"""Create the RAG methodology DOCX and PDF deliverables."""

from __future__ import annotations

import os
from pathlib import Path
import textwrap

ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".matplotlib"))

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt


DOCX_PATH = ROOT / "RAG_Methodology.docx"
PDF_PATH = ROOT / "RAG_Methodology.pdf"

NAVY = "#1F2A44"
BLUE = "#2F6FED"
GREEN = "#2E7D32"
AMBER = "#B26A00"
RED = "#B00020"
TEXT = "#222222"
MUTED = "#5C6470"
RULE = "#C8CED8"
PDF_LEFT = 0.095
PDF_RIGHT = 0.905
PDF_WIDTH_CHARS = 92

FORBIDDEN_PHRASES = (
    "ai generated",
    "ai-generated",
    "generated by",
    "generated from",
    "generated through",
    "through code",
)


CONTENT = {
    "title": "PulsePoint AI RAG Methodology",
    "subtitle": "Transparent project-health scoring for executive delivery oversight",
    "purpose": (
        "PulsePoint AI converts weekly project data into a Red/Amber/Green health status "
        "that delivery leaders can trust. The status is calculated from explicit signals, "
        "weights, thresholds, and override rules; the reasoning layer explains the fixed "
        "result and recommends action."
    ),
    "signals": [
        ("Schedule variance", "Actual progress compared with expected progress from elapsed time."),
        ("Budget burn ratio", "Budget spent relative to delivered work."),
        ("Milestone health", "Overdue milestones and near-term commitments at risk."),
        ("Blocker severity", "Open risks weighted by severity and age."),
        ("Stakeholder sentiment", "PM or client tone extracted from commentary."),
        ("Scope stability", "Scope churn applied as a penalty rather than a base score."),
    ],
    "formula": (
        "Composite = 0.25 Schedule + 0.25 Budget + 0.20 Milestones + "
        "0.20 Blockers + 0.10 Sentiment + Scope Penalty"
    ),
    "scoring_note": (
        "Each signal is normalized to a 0-100 sub-score, where 100 is healthiest. "
        "If optional data is missing, its weight is redistributed across available "
        "signals. Missing information lowers confidence rather than automatically "
        "punishing the project."
    ),
    "rag": [
        ("Green", "75-100", "On track; no material intervention required."),
        ("Amber", "50-74", "At risk; needs management attention this week."),
        ("Red", "0-49", "Off track; active intervention required."),
    ],
    "override": (
        "Override rules prevent severe risks from being hidden by averages. A critical "
        "blocker open more than 14 days or budget burn above 1.5x can force escalation."
    ),
    "data_quality": [
        "Fuzzy field matching handles variants such as % Complete, PercentComplete, and pct_done.",
        "Bad rows are returned as parse warnings instead of being silently dropped.",
        "Missing dates or budgets are treated as unknown where appropriate.",
        "A data confidence percentage is shown beside every RAG status.",
    ],
    "trust": (
        "The score is reproducible from structured inputs and scoring_config.yaml. "
        "The reasoning layer cannot change the score; it can only explain it using "
        "read-only evidence. Weekly reports include sub-scores, confidence, warnings, "
        "risks, actions, and a reasoning trace."
    ),
}


def set_default_font(document: Document) -> None:
    styles = document.styles
    normal = styles["Normal"]
    normal.font.name = "Aptos"
    normal.font.size = Pt(9.5)
    for style_name in ("Title", "Subtitle", "Heading 1", "Heading 2"):
        styles[style_name].font.name = "Aptos"


def add_doc_heading(document: Document, text: str) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(8)
    paragraph.paragraph_format.space_after = Pt(3)
    run = paragraph.add_run(text)
    run.bold = True
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor(31, 42, 68)


def add_doc_bullet(document: Document, label: str, description: str) -> None:
    paragraph = document.add_paragraph(style="List Bullet")
    paragraph.paragraph_format.left_indent = Inches(0.18)
    paragraph.paragraph_format.space_after = Pt(1)
    paragraph.paragraph_format.line_spacing = 1.0
    label_run = paragraph.add_run(f"{label}: ")
    label_run.bold = True
    paragraph.add_run(description)


def build_docx() -> None:
    document = Document()
    section = document.sections[0]
    section.page_width = Inches(8.27)
    section.page_height = Inches(11.69)
    section.top_margin = Inches(0.55)
    section.bottom_margin = Inches(0.5)
    section.left_margin = Inches(0.6)
    section.right_margin = Inches(0.6)
    set_default_font(document)

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    title.paragraph_format.space_after = Pt(0)
    run = title.add_run(CONTENT["title"])
    run.bold = True
    run.font.size = Pt(20)
    run.font.color.rgb = RGBColor(31, 42, 68)

    subtitle = document.add_paragraph()
    subtitle.paragraph_format.space_after = Pt(6)
    run = subtitle.add_run(CONTENT["subtitle"])
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(92, 100, 112)

    add_doc_heading(document, "Purpose")
    paragraph = document.add_paragraph(CONTENT["purpose"])
    paragraph.paragraph_format.line_spacing = 1.05
    paragraph.paragraph_format.space_after = Pt(4)

    add_doc_heading(document, "Core Signals")
    table = document.add_table(rows=3, cols=2)
    table.autofit = True
    for index, (label, description) in enumerate(CONTENT["signals"]):
        cell = table.cell(index % 3, index // 3)
        paragraph = cell.paragraphs[0]
        paragraph.paragraph_format.space_after = Pt(1)
        label_run = paragraph.add_run(f"{label}: ")
        label_run.bold = True
        paragraph.add_run(description)

    add_doc_heading(document, "Scoring Model")
    paragraph = document.add_paragraph(CONTENT["scoring_note"])
    paragraph.paragraph_format.line_spacing = 1.05
    formula = document.add_paragraph()
    formula.paragraph_format.left_indent = Inches(0.18)
    formula.paragraph_format.space_before = Pt(2)
    formula.paragraph_format.space_after = Pt(4)
    run = formula.add_run(CONTENT["formula"])
    run.bold = True
    run.font.color.rgb = RGBColor(47, 111, 237)

    add_doc_heading(document, "RAG Interpretation")
    rag_table = document.add_table(rows=1, cols=3)
    headers = ("Status", "Score", "Meaning")
    for i, header in enumerate(headers):
        run = rag_table.rows[0].cells[i].paragraphs[0].add_run(header)
        run.bold = True
    for status, score, meaning in CONTENT["rag"]:
        row = rag_table.add_row().cells
        row[0].text = status
        row[1].text = score
        row[2].text = meaning
    paragraph = document.add_paragraph(CONTENT["override"])
    paragraph.paragraph_format.line_spacing = 1.05

    add_doc_heading(document, "Data Quality Rules")
    for item in CONTENT["data_quality"]:
        paragraph = document.add_paragraph(item, style="List Bullet")
        paragraph.paragraph_format.left_indent = Inches(0.18)
        paragraph.paragraph_format.space_after = Pt(1)

    add_doc_heading(document, "Why This Is Trustworthy")
    paragraph = document.add_paragraph(CONTENT["trust"])
    paragraph.paragraph_format.line_spacing = 1.05

    section = document.add_section(WD_SECTION.CONTINUOUS)
    footer = section.footer.paragraphs[0]
    footer.text = "PulsePoint AI | RAG Methodology"
    footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    document.save(DOCX_PATH)


def read_docx_text() -> str:
    document = Document(DOCX_PATH)
    parts: list[str] = []
    for paragraph in document.paragraphs:
        parts.append(paragraph.text)
    for table in document.tables:
        for row in table.rows:
            for cell in row.cells:
                parts.append(cell.text)
    return "\n".join(parts)


def validate_docx() -> None:
    text = read_docx_text().lower()
    for phrase in FORBIDDEN_PHRASES:
        if phrase in text:
            raise ValueError(f"Forbidden phrase found in DOCX: {phrase}")


def add_pdf_text(
    ax: plt.Axes,
    x: float,
    y: float,
    text: str,
    width: int,
    *,
    size: float = 8.3,
    weight: str = "normal",
    color: str = TEXT,
    line_gap: float = 0.0165,
) -> float:
    for line in textwrap.wrap(text, width=width):
        ax.text(
            x,
            y,
            line,
            transform=ax.transAxes,
            fontsize=size,
            fontweight=weight,
            color=color,
            va="top",
            family="DejaVu Sans",
        )
        y -= line_gap
    return y


def add_pdf_section(ax: plt.Axes, x: float, y: float, title: str) -> float:
    ax.text(
        x,
        y,
        title,
        transform=ax.transAxes,
        fontsize=10.2,
        fontweight="bold",
        color=NAVY,
        va="top",
        family="DejaVu Sans",
    )
    ax.plot([x, PDF_RIGHT], [y - 0.016, y - 0.016], transform=ax.transAxes, color=RULE, linewidth=0.7)
    return y - 0.036


def build_pdf() -> None:
    # The Word source remains A4. The PDF uses a slightly taller one-page
    # executive layout so the margins and spacing stay clean.
    fig, ax = plt.subplots(figsize=(8.5, 13.0))
    ax.set_position([0, 0, 1, 1])
    ax.set_axis_off()
    fig.patch.set_facecolor("white")

    ax.text(PDF_LEFT, 0.952, CONTENT["title"], transform=ax.transAxes, fontsize=17.5, fontweight="bold", color=NAVY, va="top")
    ax.text(PDF_LEFT, 0.928, CONTENT["subtitle"], transform=ax.transAxes, fontsize=9.1, color=MUTED, va="top")
    ax.plot([PDF_LEFT, PDF_RIGHT], [0.904, 0.904], transform=ax.transAxes, color=NAVY, linewidth=1.1)

    y = add_pdf_section(ax, PDF_LEFT, 0.876, "Purpose")
    y = add_pdf_text(ax, PDF_LEFT, y, CONTENT["purpose"], PDF_WIDTH_CHARS, size=8.7, line_gap=0.018)
    y -= 0.018

    y = add_pdf_section(ax, PDF_LEFT, y, "Core Signals")
    for label, description in CONTENT["signals"]:
        y = add_pdf_text(ax, PDF_LEFT + 0.015, y, f"- {label}: {description}", PDF_WIDTH_CHARS - 4, size=8.2, line_gap=0.016)
        y -= 0.002
    y -= 0.014

    y = add_pdf_section(ax, PDF_LEFT, y, "Scoring Model")
    y = add_pdf_text(ax, PDF_LEFT, y, CONTENT["scoring_note"], PDF_WIDTH_CHARS, size=8.4, line_gap=0.017)
    y -= 0.006
    y = add_pdf_text(ax, PDF_LEFT + 0.02, y, CONTENT["formula"], PDF_WIDTH_CHARS - 8, size=8.5, weight="bold", color=BLUE, line_gap=0.017)
    y -= 0.018

    y = add_pdf_section(ax, PDF_LEFT, y, "RAG Interpretation")
    colors = {"Green": GREEN, "Amber": AMBER, "Red": RED}
    for status, score, meaning in CONTENT["rag"]:
        ax.text(PDF_LEFT + 0.015, y, status, transform=ax.transAxes, fontsize=8.6, fontweight="bold", color=colors[status], va="top")
        ax.text(PDF_LEFT + 0.12, y, score, transform=ax.transAxes, fontsize=8.3, fontweight="bold", color=TEXT, va="top")
        y = add_pdf_text(ax, PDF_LEFT + 0.25, y, meaning, 62, size=8.3, line_gap=0.0165)
        y -= 0.004
    y -= 0.006
    y = add_pdf_text(ax, PDF_LEFT, y, CONTENT["override"], PDF_WIDTH_CHARS, size=8.4, line_gap=0.017)
    y -= 0.018

    y = add_pdf_section(ax, PDF_LEFT, y, "Data Quality Rules")
    for item in CONTENT["data_quality"]:
        y = add_pdf_text(ax, PDF_LEFT + 0.015, y, f"- {item}", PDF_WIDTH_CHARS - 4, size=8.2, line_gap=0.016)
        y -= 0.003
    y -= 0.015

    y = add_pdf_section(ax, PDF_LEFT, y, "Why This Is Trustworthy")
    y = add_pdf_text(ax, PDF_LEFT, y, CONTENT["trust"], PDF_WIDTH_CHARS, size=8.4, line_gap=0.017)
    if y < 0.045:
        raise ValueError("PDF content is too tall for the one-page PDF layout.")

    ax.text(PDF_RIGHT, 0.047, "PulsePoint AI | RAG Methodology", transform=ax.transAxes, fontsize=7.3, color=MUTED, ha="right")

    with PdfPages(PDF_PATH) as pdf:
        pdf.savefig(fig)
    plt.close(fig)


def validate_pdf_source_text() -> None:
    source_text = "\n".join(
        str(value)
        for value in CONTENT.values()
    ).lower()
    for phrase in FORBIDDEN_PHRASES:
        if phrase in source_text:
            raise ValueError(f"Forbidden phrase found in PDF source text: {phrase}")


def main() -> None:
    build_docx()
    validate_docx()
    validate_pdf_source_text()
    build_pdf()
    print(f"Wrote {DOCX_PATH}")
    print(f"Wrote {PDF_PATH}")


if __name__ == "__main__":
    main()
