/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSynthesisRouteImport } from './routes/app.synthesis'
import { Route as AppScoringConfigRouteImport } from './routes/app.scoring-config'
import { Route as AppSchedulerRouteImport } from './routes/app.scheduler'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppDemoRouteImport } from './routes/app.demo'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAuditLogRouteImport } from './routes/app.audit-log'
import { Route as AppAskRouteImport } from './routes/app.ask'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSynthesisRoute = AppSynthesisRouteImport.update({
  id: '/synthesis',
  path: '/synthesis',
  getParentRoute: () => AppRoute,
} as any)
const AppScoringConfigRoute = AppScoringConfigRouteImport.update({
  id: '/scoring-config',
  path: '/scoring-config',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulerRoute = AppSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoRoute = AppDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/ask': typeof AppAskRoute
  '/app/audit-log': typeof AppAuditLogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/demo': typeof AppDemoRoute
  '/app/health': typeof AppHealthRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/scheduler': typeof AppSchedulerRoute
  '/app/scoring-config': typeof AppScoringConfigRoute
  '/app/synthesis': typeof AppSynthesisRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/ask': typeof AppAskRoute
  '/app/audit-log': typeof AppAuditLogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/demo': typeof AppDemoRoute
  '/app/health': typeof AppHealthRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/scheduler': typeof AppSchedulerRoute
  '/app/scoring-config': typeof AppScoringConfigRoute
  '/app/synthesis': typeof AppSynthesisRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/ask': typeof AppAskRoute
  '/app/audit-log': typeof AppAuditLogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/demo': typeof AppDemoRoute
  '/app/health': typeof AppHealthRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/scheduler': typeof AppSchedulerRoute
  '/app/scoring-config': typeof AppScoringConfigRoute
  '/app/synthesis': typeof AppSynthesisRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/alerts'
    | '/app/ask'
    | '/app/audit-log'
    | '/app/dashboard'
    | '/app/demo'
    | '/app/health'
    | '/app/projects'
    | '/app/reports'
    | '/app/scheduler'
    | '/app/scoring-config'
    | '/app/synthesis'
    | '/app/'
    | '/app/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/alerts'
    | '/app/ask'
    | '/app/audit-log'
    | '/app/dashboard'
    | '/app/demo'
    | '/app/health'
    | '/app/projects'
    | '/app/reports'
    | '/app/scheduler'
    | '/app/scoring-config'
    | '/app/synthesis'
    | '/app'
    | '/app/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/alerts'
    | '/app/ask'
    | '/app/audit-log'
    | '/app/dashboard'
    | '/app/demo'
    | '/app/health'
    | '/app/projects'
    | '/app/reports'
    | '/app/scheduler'
    | '/app/scoring-config'
    | '/app/synthesis'
    | '/app/'
    | '/app/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/synthesis': {
      id: '/app/synthesis'
      path: '/synthesis'
      fullPath: '/app/synthesis'
      preLoaderRoute: typeof AppSynthesisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scoring-config': {
      id: '/app/scoring-config'
      path: '/scoring-config'
      fullPath: '/app/scoring-config'
      preLoaderRoute: typeof AppScoringConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scheduler': {
      id: '/app/scheduler'
      path: '/scheduler'
      fullPath: '/app/scheduler'
      preLoaderRoute: typeof AppSchedulerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demo': {
      id: '/app/demo'
      path: '/demo'
      fullPath: '/app/demo'
      preLoaderRoute: typeof AppDemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-log': {
      id: '/app/audit-log'
      path: '/audit-log'
      fullPath: '/app/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ask': {
      id: '/app/ask'
      path: '/ask'
      fullPath: '/app/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAskRoute: typeof AppAskRoute
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDemoRoute: typeof AppDemoRoute
  AppHealthRoute: typeof AppHealthRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSchedulerRoute: typeof AppSchedulerRoute
  AppScoringConfigRoute: typeof AppScoringConfigRoute
  AppSynthesisRoute: typeof AppSynthesisRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAskRoute: AppAskRoute,
  AppAuditLogRoute: AppAuditLogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDemoRoute: AppDemoRoute,
  AppHealthRoute: AppHealthRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSchedulerRoute: AppSchedulerRoute,
  AppScoringConfigRoute: AppScoringConfigRoute,
  AppSynthesisRoute: AppSynthesisRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
